<div class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
	<div class="collapse navbar-collapse">
		<ul class="navbar-nav mr-auto">

			<a class="navbar-brand" href="/tags/index" >
				<span>TagsResources</span>
			</a>

			<li class="nav-item">
				<a href="#images" class="nav-link">Images</a>
			</li>
			<li class="nav-item">
				<a href="#javascripts" class="nav-link">Javascripts</a>
			</li>
			<li class="nav-item">
				<a href="#styles" class="nav-link">Styles</a>
			</li>

		
		</ul>
	</div>
</div>