<!DOCTYPE html>
<html>
<head>
	<?php $this->get_template("header.phtml"); ?>
	<?php $this->add_script_server("schemadb", "tables/form.js"); ?>
</head>
<body>
	
	<?php $this->get_template("navbar.phtml"); ?>

	<div class="container" id="main-schema">

		<div class="container">
			<form id="form-create-table" method="POST" action="javascript:create_table();">

				<div class="row">
					<div class="modal-title">
						<h2>Nueva Tabla</h2>
					</div>
				</div>
			
				<div class="row">
					<input type="text" class="form-control" name="table[name]" id = "name-table" placeholder="Nombre de la tabla">
				</div>

				<div id="fields">
					
					<div class="row">
				
						<div class="col">
							<input type="text" placeholder="Field" name = "table[fields][name][]" class="form-control form-sm" id = "name-field" />
						</div>

						<div class="col">
							<select type="text" class="form-control form-sm" name="table[fields][type][]" />
								<option>string</option>
								<option>text</option>
								<option>bool</option>
								<option>integer</option>
								<option>biginteger</option>
								<option>float</option>
								<option>double</option>
								<option>decimal</option>
								<option>date</option>
								<option>datetime</option>
								<option>time</option>
								<option>year</option>
								<option>references</option>
							</select>
						</div>

						<div class="col">
							<input type="text" class="form-control" name = "table[fields][quantity][]" placeholder="cantidad" />
						</div>
			
					</div>

				</div>

				<div class="row modal-footer" id = "footer-form-create">

					<button type="button" class="btn btn-primary" onclick="insert_fields_form();">
						<span class="close">+</span> Agregar
					</button>

					<button type="submit" class="btn btn-info">
						<span class="close">{}</span> Crear Tabla
					</button>

				</div>

			</form>

		</div>

	</div>

</body>
</html>